version: '2'
services:

  mysql:
    image: mysql:8.0.29
    container_name: ruoyi-mysql
    hostname: ruoyi-mysql
    environment:
      MYSQL_ROOT_PASSWORD: N8vV9modVBznVFXq
      # 不在此处建库，使用 bin/init_db.sh|ps1 建库
      # MYSQL_DATABASE: ruoyi_db
      # MYSQL_USER: super_admin
      # MYSQL_PASSWORD: YrP9BfHvDvZTQiux
    command: [ "--default-authentication-plugin=mysql_native_password", "--character-set-server=utf8mb4" ]
    volumes:
      - ./volumes/mysql/conf/docker.cnf:/etc/mysql/conf.d/docker.cnf
      - ./volumes/mysql/data:/var/lib/mysql
      - shared-tmp:/tmp
    ports:
      - 127.0.0.1:3306:3306
    networks:
      ruoyi-net:
        ipv4_address: 172.168.100.2
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
    # 忽略 docker 运行时的安全认证
    security_opt:
      - seccomp:unconfined
    restart: on-failure


  redis:
    image: redis:6.2.6
    container_name: ruoyi-redis
    hostname: ruoyi-redis
    ports:
      - 127.0.0.1:6379:6379
    volumes:
      - ./volumes/redis/conf/redis.conf:/etc/redis/redis.conf
      - ./volumes/redis/data:/data
    command: [ 'redis-server', '/etc/redis/redis.conf' ]
    networks:
      ruoyi-net:
        ipv4_address: 172.168.100.3
    restart: on-failure

  ruoyi-app:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        APP_DIR: ruoyi
        APP_JAR: ruoyi.jar
    container_name: ruoyi-app
    hostname: centos
    environment:
      - TZ=Asia/Shanghai
      - LANG=zh_CN.UTF-8
      - LANGUAGE=zh_CN.UTF-8
      - LC_ALL=zh_CN.UTF-8
      # 配置文件中密码的解压密码
      - JASYPT_ENCRYPTOR_PASSWORD=${JASYPT_PWD}
      # jar 包的解密密码，maven 编译时的密码保持一致，请勿泄露给渗透测试人员或随意变更，否则无法解密
      - CONFUSE_PWD=${CONFUSE_PWD}
      - CONFUSE_PATH=/var/lib/apt/lists/.lock
    volumes:
      - ./logs:/var/cache/ruoyi/logs
    # 接入 ruoyi-nginx 访问，不暴露端口
    # ports:
    #   - 127.0.0.1:8253:8080
    networks:
      ruoyi-net:
        ipv4_address: 172.168.100.253
    depends_on:
      - mysql
      - redis
    restart: on-failure


networks:
  ruoyi-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet:  172.168.100.0/24
          gateway: 172.168.100.1


