CREATE DATABASE IF NOT EXISTS `app_db` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

use `app_db`;

CREATE USER 'app_admin'@'%' IDENTIFIED BY 'YrP9BfHvDvZTQiux';
GRANT USAGE ON *.* TO 'app_admin'@'%' WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
GRANT ALL PRIVILEGES ON `app_db`.* TO 'app_admin'@'%';
